### ISSUE TITLE
Creating simple flow turning on build in LED does not work

### ISSUE THREAD

**Issue by rhannink** [athombv/com.athom.homeyduino#32]
I have implemented the rc example on an ESP8266. I can add the module to Homey and I define D0 (GPIO 16) as an output.

Next I create a flow which turns the LED on. When I test the flow the action card spins and then an error.

Am I doing something wrong here?

I am using Homey app version 0.9.6 and I have changed **numAnalogPins** to **numAnalogInputs** the ESP8266 directory so it works.

**Comment by renzenicolai** [comment]
Hello rhannink,

I guess you were using a Wemos D1 r2 or mini.

The problem should be fixed now, please try again!

The numAnalogPins was a bug, and should have been numAnalogInputs.
Also on the Arduino side the library did not correctly allocate the pin mapping for Dx to GPIOx on some boards. I've added overrides for these boards so that the list is allocated correctly.

Greetings,
Renze Nicolai
